language: node_js
dist: xenial

addons:
  snaps:
    - doctl
    - name: kubectl
      confinement: classic

services:
  - docker

before_install:
  - ./.travis/docker.sh
  - ./.travis/kubernetes.sh

install:
  - docker-compose up -d postgres prisma

script:
  - yarn run test

deploy:
  provider: script
  script: ./.travis/deploy.sh
  on:
    branch: Travis
