language: node_js
node_js:
  - "10.14.1"
dist: xenial

addons:
  snaps:
    - doctl
    - name: kubectl
      confinement: classic

services:
  - docker

before_install:
  - ./.travis/docker.sh
  - ./.travis/kubernetes.sh

install:
  - docker-compose up -d postgres prisma
  - npm install -g typescript
  - npm install -g prisma
  - prisma deploy
  - yarn install

script:
  - yarn run test

deploy:
  provider: script
  script: ./.travis/deploy.sh
  on:
    branch: Travis
