language: node_js
dist: xenial

addons:
  snaps:
    - doctl
    - name: kubectl
      confinement: classic

services:
  - docker

install:
  - mkdir ${HOME}/.kube
  - doctl kubernetes cluster kubeconfig save $CLUSTER_NAME
  - mv /home/travis/snap/doctl/64/.kube/config ${HOME}/.kube/config
  - ls -lha /home/travis/snap/
  - ls -lha ${HOME}/.kube/
  - cat ${HOME}/.kube/config
  - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  - docker-compose up -d

deploy:
  provider: script
  script: ./.travis/deploy.sh
  on:
    branch: staging
