version: '2.1'
services:
  api:
    build: .
    user: root
    restart: always
    container_name: nadle-api
    ports:
      - "4000:4000"
    depends_on:
      prisma:
        condition: service_healthy
    environment:
      BONSAI_URL: http://elasticsearch:9200/
      CLOUDCUBE_URL: http://s3:4569/
      DATABASE_URL: postgres://prisma:prisma@postgres:5432/nadle
      PRISMA_URL: http://prisma:4466/
      S3_BUCKET: nadle
      S3_ENDPOINT: http://s3:4569/
      SECRET: 33fd1317-8acf-48bc-9d8b-a53988ea0c07
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    healthcheck:
      test: ["CMD-SHELL", "wget --spider localhost:4466 || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            user: prisma
            password: prisma
            rawAccess: true
            port: 5432
            migrations: true
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elasticsearch1
    environment:
      - node.name=elasticsearch1
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elasticsearch1
      - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
  s3:
    image: lphoward/fake-s3
    ports:
      - "4569:4569"
    volumes:
      - s3:/fakes3_root


volumes:
  postgres:
  s3:
