version: '2.1'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    networks:
      - api
    healthcheck:
      test: ["CMD-SHELL", "wget --spider localhost:4466 || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            user: prisma
            password: prisma
            rawAccess: true
            port: 5432
            migrations: true
  postgres:
    image: postgres
    restart: always
    # Uncomment the next two lines to connect to your your database from outside the Docker environment, e.g. using a database GUI like Postico
    # ports:
    # - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - api
  api:
    build: .
    user: root
    restart: always
    container_name: nadle-api
    ports:
      - "3000:3000"
      - "4000:4000"
    networks:
      - api
    depends_on:
      prisma:
        condition: service_healthy
    
volumes:
  postgres:

networks:
  api:
    driver: bridge
